version: '3.9'

services:
  backend:
    build: ./backEnd 
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 11nacho04
      MYSQL_DATABASE: sign_up
    depends_on:
      - db

  frontend:
    build: ./loginFrontEnd
    ports:
      - "3000:5000"
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 11nacho04
      MYSQL_DATABASE: sign_up
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: