name: Build and Deploy to Azure Web App - AdminMate-backend

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'  # Ensure this matches the Node.js version in Azure

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Run tests
      run: |
        cd backend
        npm test  # Adjust or remove if you don't have tests

    - name: Build the project
      run: |
        cd backend
        npm run build  # Adjust if your backend requires a build step

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app
        path: backend

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: 'AdminMate-backend'
        slot-name: 'Production'
        package: backend